CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(40) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tweets (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    content VARCHAR(280) NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_TWEETS_USER_USER_ID FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX IX_TWEETS_USER_ID ON tweets (user_id);

CREATE TABLE IF NOT EXISTS followers (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    follower_user_id BIGINT NOT NULL,
    CONSTRAINT FK_FOLLOWERS_USERS_USER_ID FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT FK_FOLLOWERS_USERS_FOLLOWER_USER_ID FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE UNIQUE INDEX UIX_FOLLOWERS_USER_ID_FOLLOWER_USER_ID ON followers (user_id, follower_user_id);
CREATE INDEX IX_FOLLOWERS_FOLLOWER_USER_ID ON followers (follower_user_id);