INSERT INTO users (username) VALUES
                                 ('nahuel'),
                                 ('taylorswift'),
                                 ('bill-gates'),
                                 ('jeff-bezos'),
                                 ('sundar-pichai'),
                                 ('mark-zuckerberg'),
                                 ('tim-cook'),
                                 ('susan-wojcicki'),
                                 ('oprah'),
                                 ('kanye-west'),
                                 ('kim-kardashian'),
                                 ('lebron-james'),
                                 ('serena-williams'),
                                 ('michael-jordan'),
                                 ('mariah-carey'),
                                 ('drake'),
                                 ('adele'),
                                 ('lady-gaga'),
                                 ('ariana-grande'),
                                 ('justin-bieber'),
                                 ('kylie-jenner'),
                                 ('kendall-jenner'),
                                 ('zayn-malik'),
                                 ('shakira'),
                                 ('cristiano-ronaldo'),
                                 ('leo-messi'),
                                 ('roger-federer'),
                                 ('usain-bolt'),
                                 ('elon-replica'),
                                 ('rihanna-replica'),
                                 ('user1'),
                                 ('user2'),
                                 ('user3'),
                                 ('user4'),
                                 ('user5'),
                                 ('user6'),
                                 ('user7'),
                                 ('user8'),
                                 ('user9'),
                                 ('user10'),
                                 ('user11'),
                                 ('user12'),
                                 ('user13'),
                                 ('user14'),
                                 ('user15'),
                                 ('user16'),
                                 ('user17'),
                                 ('user18'),
                                 ('user19'),
                                 ('user20'),
                                 ('user21'),
                                 ('user22'),
                                 ('user23'),
                                 ('user24'),
                                 ('user25'),
                                 ('user26'),
                                 ('user27'),
                                 ('user28'),
                                 ('user29'),
                                 ('user30'),
                                 ('user31'),
                                 ('user32'),
                                 ('user33'),
                                 ('user34'),
                                 ('user35'),
                                 ('user36'),
                                 ('user37'),
                                 ('user38'),
                                 ('user39'),
                                 ('user40'),
                                 ('user41'),
                                 ('user42'),
                                 ('user43'),
                                 ('user44'),
                                 ('user45'),
                                 ('user46'),
                                 ('user47'),
                                 ('user48'),
                                 ('user49'),
                                 ('user50'),
                                 ('user51'),
                                 ('user52'),
                                 ('user53'),
                                 ('user54'),
                                 ('user55'),
                                 ('user56'),
                                 ('user57'),
                                 ('user58'),
                                 ('user59'),
                                 ('user60'),
                                 ('user61'),
                                 ('user62'),
                                 ('user63'),
                                 ('user64'),
                                 ('user65'),
                                 ('user66'),
                                 ('user67'),
                                 ('user68'),
                                 ('user69'),
                                 ('user70'),
                                 ('user71'),
                                 ('user72'),
                                 ('user73'),
                                 ('user74'),
                                 ('user75'),
                                 ('user76'),
                                 ('user77'),
                                 ('user78'),
                                 ('user79'),
                                 ('user80'),
                                 ('user81'),
                                 ('user82'),
                                 ('user83'),
                                 ('user84'),
                                 ('user85'),
                                 ('user86'),
                                 ('user87'),
                                 ('user88'),
                                 ('user89'),
                                 ('user90'),
                                 ('user91'),
                                 ('user92'),
                                 ('user93'),
                                 ('user94'),
                                 ('user95'),
                                 ('user96'),
                                 ('user97'),
                                 ('user98'),
                                 ('user99'),
                                 ('user100')
ON CONFLICT DO NOTHING ;

INSERT INTO followers (user_id, follower_user_id) VALUES
                                                      (3, 1), (3, 2), (3, 4), (3, 5), (1, 3), (1, 4), (2, 1), (2, 5),
                                                      (4, 6), (5, 2), (11, 10), (11, 12), (11, 13), (22, 21), (22, 23),
                                                      (18, 19), (19, 20), (20, 21), (21, 18), (7, 1), (8, 2), (9, 3),
                                                      (10, 4), (11, 5), (12, 6), (13, 7), (14, 8), (15, 9), (16, 10),
                                                      (17, 11), (18, 12), (19, 13), (20, 14), (21, 15), (22, 16),
                                                      (23, 17), (24, 18), (25, 19), (26, 20), (27, 21), (28, 22),
                                                      (29, 23), (30, 24), (31, 25), (32, 26), (33, 27), (34, 28),
                                                      (35, 29), (36, 30), (37, 31), (38, 32), (39, 33), (40, 34),
                                                      (41, 35), (42, 36), (43, 37), (44, 38), (45, 39), (46, 40),
                                                      (47, 41), (48, 42), (49, 43), (50, 44), (51, 45), (52, 46),
                                                      (53, 47), (54, 48), (55, 49), (56, 50), (57, 51), (58, 52),
                                                      (59, 53), (60, 54), (61, 55), (62, 56), (63, 57), (64, 58),
                                                      (65, 59), (66, 60), (67, 61), (68, 62), (69, 63), (70, 64),
                                                      (71, 65), (72, 66), (73, 67), (74, 68), (75, 69), (76, 70),
                                                      (77, 71), (78, 72), (79, 73), (80, 74), (81, 75), (82, 76),
                                                      (83, 77), (84, 78), (85, 79), (86, 80), (87, 81), (88, 82),
                                                      (89, 83), (90, 84), (91, 85), (92, 86), (93, 87), (94, 88),
                                                      (95, 89), (96, 90), (97, 91), (98, 92), (99, 93), (100, 94),
                                                      (1, 95), (2, 96), (3, 97), (4, 98), (5, 99), (6, 100),
                                                      (7, 1), (8, 2), (9, 3), (10, 4), (11, 5), (12, 6), (13, 7),
                                                      (14, 8), (15, 9), (16, 10), (17, 11), (18, 12), (19, 13),
                                                      (20, 14), (21, 15), (22, 16), (23, 17), (24, 18), (25, 19),
                                                      (26, 20), (27, 21), (28, 22), (29, 23), (30, 24)
ON CONFLICT DO NOTHING ;

INSERT INTO tweets (user_id, content) VALUES
                                          (1, 'Tweet 1 from user 1'), (2, 'Tweet 1 from user 2'),
                                          (3, 'Tweet 1 from user 3'), (4, 'Tweet 1 from user 4'),
                                          (5, 'Tweet 1 from user 5'), (6, 'Tweet 1 from user 6'),
                                          (7, 'Tweet 1 from user 7'), (8, 'Tweet 1 from user 8'),
                                          (9, 'Tweet 1 from user 9'), (10, 'Tweet 1 from user 10'),
                                          (11, 'Tweet 1 from user 11'), (12, 'Tweet 1 from user 12'),
                                          (13, 'Tweet 1 from user 13'), (14, 'Tweet 1 from user 14'),
                                          (15, 'Tweet 1 from user 15'), (16, 'Tweet 1 from user 16'),
                                          (17, 'Tweet 1 from user 17'), (18, 'Tweet 1 from user 18'),
                                          (19, 'Tweet 1 from user 19'), (20, 'Tweet 1 from user 20'),
                                          (21, 'Tweet 1 from user 21'), (22, 'Tweet 1 from user 22'),
                                          (23, 'Tweet 1 from user 23'), (24, 'Tweet 1 from user 24'),
                                          (25, 'Tweet 1 from user 25'), (26, 'Tweet 1 from user 26'),
                                          (27, 'Tweet 1 from user 27'), (28, 'Tweet 1 from user 28'),
                                          (29, 'Tweet 1 from user 29'), (30, 'Tweet 1 from user 30'),
                                          (31, 'Tweet 1 from user 31'), (32, 'Tweet 1 from user 32'),
                                          (33, 'Tweet 1 from user 33'), (34, 'Tweet 1 from user 34'),
                                          (35, 'Tweet 1 from user 35'), (36, 'Tweet 1 from user 36'),
                                          (37, 'Tweet 1 from user 37'), (38, 'Tweet 1 from user 38'),
                                          (39, 'Tweet 1 from user 39'), (40, 'Tweet 1 from user 40'),
                                          (41, 'Tweet 1 from user 41'), (42, 'Tweet 1 from user 42'),
                                          (43, 'Tweet 1 from user 43'), (44, 'Tweet 1 from user 44'),
                                          (45, 'Tweet 1 from user 45'), (46, 'Tweet 1 from user 46'),
                                          (47, 'Tweet 1 from user 47

'), (48, 'Tweet 1 from user 48'),
                                          (49, 'Tweet 1 from user 49'), (50, 'Tweet 1 from user 50'),
                                          (51, 'Tweet 1 from user 51'), (52, 'Tweet 1 from user 52'),
                                          (53, 'Tweet 1 from user 53'), (54, 'Tweet 1 from user 54'),
                                          (55, 'Tweet 1 from user 55'), (56, 'Tweet 1 from user 56'),
                                          (57, 'Tweet 1 from user 57'), (58, 'Tweet 1 from user 58'),
                                          (59, 'Tweet 1 from user 59'), (60, 'Tweet 1 from user 60'),
                                          (61, 'Tweet 1 from user 61'), (62, 'Tweet 1 from user 62'),
                                          (63, 'Tweet 1 from user 63'), (64, 'Tweet 1 from user 64'),
                                          (65, 'Tweet 1 from user 65'), (66, 'Tweet 1 from user 66'),
                                          (67, 'Tweet 1 from user 67'), (68, 'Tweet 1 from user 68'),
                                          (69, 'Tweet 1 from user 69'), (70, 'Tweet 1 from user 70'),
                                          (71, 'Tweet 1 from user 71'), (72, 'Tweet 1 from user 72'),
                                          (73, 'Tweet 1 from user 73'), (74, 'Tweet 1 from user 74'),
                                          (75, 'Tweet 1 from user 75'), (76, 'Tweet 1 from user 76'),
                                          (77, 'Tweet 1 from user 77'), (78, 'Tweet 1 from user 78'),
                                          (79, 'Tweet 1 from user 79'), (80, 'Tweet 1 from user 80'),
                                          (81, 'Tweet 1 from user 81'), (82, 'Tweet 1 from user 82'),
                                          (83, 'Tweet 1 from user 83'), (84, 'Tweet 1 from user 84'),
                                          (85, 'Tweet 1 from user 85'), (86, 'Tweet 1 from user 86'),
                                          (87, 'Tweet 1 from user 87'), (88, 'Tweet 1 from user 88'),
                                          (89, 'Tweet 1 from user 89'), (90, 'Tweet 1 from user 90'),
                                          (91, 'Tweet 1 from user 91'), (92, 'Tweet 1 from user 92'),
                                          (93, 'Tweet 1 from user 93'), (94, 'Tweet 1 from user 94'),
                                          (95, 'Tweet 1 from user 95'), (96, 'Tweet 1 from user 96'),
                                          (97, 'Tweet 1 from user 97'), (98, 'Tweet 1 from user 98'),
                                          (99, 'Tweet 1 from user 99'), (100, 'Tweet 1 from user 100');

-- Repitiendo con contenido variado
DO $$
BEGIN
    FOR i IN 1..50000 LOOP
        INSERT INTO tweets (user_id, content)
        VALUES (FLOOR(1 + RANDOM() * 100), 'Random tweet #' || i);
    END LOOP;
END $$;